spring:
  application:
    name: config-service

server:
  port: 9002
  servlet:
    context-path: /config

nacos:
  config:
    server-addr: localhost:8848
    namespace: dev
    group: DEFAULT_GROUP
    data-ids: config.service
    username: nacos
    password: nacos
    bootstrap:
      enable: true
    auto-refresh: true
#    enable-remote-sync-config: true